[#845] Implement extract function
This commit implements time related sql function called extract.

Functional spec (copied from doc/grammar.rst)
--------
```
 ``EXTRACT``

   Extracts a particular field from the date/time or interval. Date/time or interval is normalized before extracting the indicated
   field.

   Syntax:

   .. code-block::

     EXTRACT(field FROM value)
     field -> YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, TIMEZONE_HOUR and TIMEZONE_MINUTE
     value -> Date/time or interval values

   Return value is:
   * Null if value is NULL
   * Numeric value representing the quantity of the unit specified
```

Design
-------
* The function definition is included in octo-seed.sql
* Extract function call syntax is different from a regular function. To accommodate this syntax parser now includes
  `numeric_value_function`.
  Reference: `https://ronsavage.github.io/SQL/sql-92.bnf.html#numeric%20value%20function`.
* `EXTRACT` is included in `sql_keyword` rule. This change is done to allow `EXTRACT` to be used as name in function definition.
  This rule conflicted with `extract_expression` rules (shift/reduce conflict). It was resolved by establishing precedence between
  `PREC2` and `EXTRACT` and assigning `PREC2` to `EXTRACT` rule in `sql_keyword`. `PREC2` has lower precedence to `EXTRACT`.
  Reference: commit - 198ea7cd97.
* Overall working
  * Octo seed will add `EXTRACT` function definitions. Two definitions are added, one to allow date/time as argument and the other
    to allow interval as argument. src/parser/function_definition.c is updated to allow interval specification for this function.
    Rest of the function definition processing is similar to any other function.
  * Extract function with date/time argument is handled by `$$EXTRACT^%ydboctosqlfunctions`
  * Extract function with interval argument is handled by `$$EXTRACTINTERVAL^%ydboctosqlfunctions`
  * When a user invokes `EXTRACT`, parser creates a `function_call_STATEMENT` with name as `extract` and argument list having
    `field` and `date/time or interval`. Interval usage is enabled for this function call by allowing it
    in src/function_call_data_type_check.c.
  * Its processing until tmpl_print_expression execution is similar to any other `function_call_STATEMENT`.
  * src/m_templates/tmpl_print_expression.ctemplate, case LP_FUNCTION_CALL, is updated to identify if the M routine is
    `EXTRACT` or `EXTRACTINTERVAL`.
    If interval exists in the name then the argument is processed similar to `DATE_ADD`/`DATE_SUB`. If date/time exists then in
    addition to the two arguments(`field` and date/time value) a third argument representing the date/time text format is passed
    along to the M routine.
  * The M routines invoked call external functions `ydboctoExtractDateTimeM` and `ydboctoExtractIntervalM` with the passed arguments.
  * `ydboctoExtractDateTimeM` uses `strptime` to convert the text formatted value to `struct tm` value. Then the requested field is
    returned from the `tm` structure.
  * `ydboctoExtractIntervalM` returns the value of the field requested by looking at its argument list which has all fields of an
    interval.

Note
-----
* Cases where the expected field is not present in the date/time value generate error in Postgres but return `0` in Octo.
  Following are few such examples.
  ```
  names=> select extract(hour from date'01-01-2023');
  ERROR:  unit "hour" not supported for type date

  names=> select extract(day from time'01:01:01');
  ERROR:  unit "day" not supported for type time without time zone

  OCTO> select extract(hour from date'01-01-2023');
  extract
  0
  (1 row)
  OCTO> select extract(day from time'01:01:01');
  extract
  0
  (1 row)
  ```
* Following case returns different result in Postgres and Octo because Postgres rounds second value if sub-second
  information is greater than 9 decimal places where as Octo truncates the value.
  ```
  names=> select extract(second from interval'40.999999999 second');
    extract
  -----------
   41.000000
  (1 row)

  OCTO> select extract(second from interval'40.999999999 second');
  extract
  40.999999
  (1 row)
  ```

Testing
--------
* TIS06, TIS23, TIS24 and TIS25 of test_interval_syntax.bats.in validates this implementation
* tests/fixtures/intervalsyntax.m -> getExtractQueries is updated to include `timezone_hour` and `timezone_minute`
  fields in queries.
* test/fixtures/intervalsyntax.m -> getExtractIntervalQueries is newly added to generate interval based extract
  function queries
* Both the above routines generate extract function queries with random fields applied to random date/time or
  interval values
* Those combinations which generate error in Postgres are not generated
* All other subtest changes are a result of addition of `EXTRACT` to seed file

Doc
-----
* doc/grammar.rst is updated to include `EXTRACT` function under `INTERVAL SYNTAX`-> `functions` section